language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

branches:
  only:
  - master

before_script:
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit --configuration phpunit.xml.dist --coverage-text
